### ISSUE TITLE
support InstanceProfileCredentialsProvider

### ISSUE THREAD

**Issue by adriaanm** [sbt/sbt-s3#14]
When running on an EC2 instance, you can avoid having to generate credentials using IAM instance profiles. This is safer because it allows for more precise role-based access control.

The solution would be to fall back to an [InstanceProfileCredentialsProvider](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/InstanceProfileCredentialsProvider.html) ([example](https://github.com/adriaanm/ec2-start-stop/blob/448c7afa/src/main/scala/EC2InstanceManager.scala#L59)) when there are no credentials  available.

See http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-roles.html, http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html for more background.

**Comment by cunei** [comment]
Fixed in #19
