### ISSUE TITLE
New release any time soon?

### ISSUE THREAD

**Issue by emersonloureiro** [sbt/sbt-s3#30]
Hey folks.

Seems like the last release of sbt-s3 was just over 2 years ago - with 22 commits since then - and I'm wondering if there are plans of releasing a new version any time soon. Reason I'm asking is because I'm really interested in a version with the latest S3Plugin.scala, as it apparently contains a fix for reading AWS credentials using the default provider chain - for the case when you don't specify a .sbt/.credentials file with username password - which is exactly what I need.

Cheers

--
Emerson

**Comment by cunei** [comment]
Hello Emerson! This project has been virtually not maintained for quite a while, as you observed. I am now merging the remaining pull requests and I will issue a new release shortly. I am looking for a new maintainer, incidentally: if anybody would like to take over, I'd be glad to transfer ownership.

**Comment by emersonloureiro** [comment]
Hi there. Thanks for getting back to me. Glad there's a release coming out soon 😄 . 

I'm more than happy to be a maintainer, by the way.

**Comment by cunei** [comment]
I just pushed v0.9, although I cannot be absolutely sure all is in order at this time. Please use with caution.

**Comment by cunei** [comment]
Thanks Emerson, I'll check what needs to be done in order to transfer ownership.

**Comment by emersonloureiro** [comment]
Thanks for the release, much appreciated. I'll integrate with one of our apps soon and see how that goes.

Thanks again.

**Comment by eed3si9n** [comment]
I created sbt-s3-team and you should both have admin rights on this repo.

**Comment by emersonloureiro** [comment]
Excellent. Thanks very much.

**Comment by cunei** [comment]
I will make some additional changes tomorrow, then I will hand over the project.

**Comment by emersonloureiro** [comment]
Sounds good.

**Comment by cunei** [comment]
I changed organization and name, as requested by @eed3si9n. @emersonloureiro, you can create a new package in Bintray and ask for it to be linked to sbt/sbt-plugin-releases, then publish new versions there. The project is now yours!

**Comment by emersonloureiro** [comment]
Sounds good, thanks!
