### ISSUE TITLE
Example in README lacking...

### ISSUE THREAD

**Issue by a1russell** [sbt/sbt-s3#44]
The example in your README is lacking the `S3Plugin.s3Settings` line that's necessary to run the `s3Upload` task.

Or even better would be, since this is supposed to be an auto plugin, to automatically add these settings.

**Comment by emersonloureiro** [comment]
Apologies for the delay on replying to this. I'm reviewing https://github.com/sbt/sbt-s3/pull/45 now, and will release a new version later on today.

**Comment by emersonloureiro** [comment]
Version 0.10.2 is out now.

**Comment by a1russell** [comment]
Thank you!
