### ISSUE TITLE
s3Upload not working

### ISSUE THREAD

**Issue by Timunas** [sbt/sbt-s3#53]
Hi,

I'm trying to use this plugin in order to upload some files into an aws s3 bucket, however I'm not being capable of using it.

I have a multiproject sbt configuration and I defined in one of the subprojects and it seems that the file upload is not working properly.

My configuration: 
```
val techDocumentation =
Project(id = "tech-documentation", base = file("tech-documentation"))
.settings(techDocumentationSettings)
.enablePlugins(S3Plugin)

lazy val techDocumentationSettings = sharedSettings ++ Seq(
  name                         := "tech-documentation",
  // Do not publish anything
  publishArtifact in (Compile, packageBin) := false,
  publishArtifact in (Compile, packageDoc) := false,
  s3Host in s3Upload         := "awesome-docs",
  s3Progress in s3Upload  := true,
  mappings in s3Upload     := tasks.buildDocs.value
)
```

I tried both running sbt s3-upload or sbt s3Upload without success.
It says it is not a valid command.

> error] Not a valid command: s3-upload (similar: loadp, reload)
[error] Not a valid project ID: s3-upload
[error] Expected ':' (if selecting a configuration)
[error] Expected '::'
[error] Not a valid key: s3-upload (similar: on-unload, on-load, test-loader)
[error] s3-upload

Using version 0.10 and sbt 0.13.15

**Comment by LiadBerko** [comment]
Hi Timunas, did you manage to solve that?

**Comment by odenzo** [comment]
s3Upload command seems to be the command.

**Comment by emersonloureiro** [comment]
Looks like just the task was incorrect, resolving.
