### ISSUE TITLE
Post Bintray

### ISSUE THREAD

**Issue by flurdy** [sbt/sbt-s3#67]
Any plans to migrate the packages to somewhere else post the Bintray sunsetting?

 https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by gheine** [comment]
+1 

https://dl.bintray.com/emersonloureiro/sbt-plugins/cf.janga/sbts3/scala_2.12/sbt_1.0/0.10.3/ivys/ivy.xml has become inaccessible today.

**Comment by emersonloureiro** [comment]
Apologies I missed the deadline to migrate the project elsewhere. I'll look into that now.

**Comment by emersonloureiro** [comment]
Issue is now fixed. README updated with the new repository. Migrated to sonatype.

**Comment by emersonloureiro** [comment]
Please give it a try now - I did, it worked- and let me know if it's not working.

**Comment by gheine** [comment]
You're a rockstar @emersonloureiro! Thank you!!!

**Comment by emersonloureiro** [comment]
Will close this issue since it's resolved. Re-open if there are any troubles.
