### ISSUE TITLE
Question about how to use variables in build.sbt

### ISSUE THREAD

**Issue by jameswu0629** [sbt/sbt-s3#7]
Hi,

I am a newbie and wanna ask for some advanced rules for my build sbt definitions. 
Here is part of my file:

import S3._

name := "MyProject"

version := "1.0.0"

s3Settings

mappings in upload := Seq((new java.io.File("./MyProject-1.0.0.tar.gz"), "repo/MyProject-1.0.0.tar.gz"))

host in upload := "mybuket.s3.amazonaws.com"

credentials += Credentials(Path.userHome / ".s3credentials")

I am wondering how to use the settings: name & version to compose "MyProject-1.0.0.tar.gz" ? That's because if next time I want to upgrade my build to 1.0.1, I only need to change the value of the version.

Thanks.

**Comment by EricQuinterX** [comment]
Works with **s""**
example:
```
version := "1.0"
assemblyJarName := s"AppName v${version.value}"
```

**Comment by matanster** [comment]
No longer applicable in SBT 1.x it seems
